name = "LabViewXML"
uuid = "656e9f32-718a-11e9-002e-018f26774860"
authors = ["MLackner <lacknersmichael@gmail.com>"]
version = "0.1.0"

[deps]
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]

[compat]
julia = "^1.0"
LightXML = "^0.9"
